### ISSUE TITLE
CorePlot.h Dependency 

### ISSUE THREAD

**Issue by SethCalkins** [dsouzarc/iMessageAnalyzer#1]
Building iMessageAnalyzer GraphViewController.h 

I'm receiving a dependency error `CorePlot/CorePlot.h file not found`

[Line of Code Triggering Error](https://github.com/dsouzarc/iMessageAnalyzer/blob/6c1fc24e7566e4293ebabf7e1c8d3efb8499df63/iMessageAnalyzer/GraphViewController.h#L11)

**Comment by dsouzarc** [comment]
Hey, sorry to get back to you so late but I fixed that issue with CorePlot. Check out the latest version
