### ISSUE TITLE
Crash with huge message bank

### ISSUE THREAD

**Issue by ritvikupadhyaya** [dsouzarc/iMessageAnalyzer#2]
The app crashed multiple times when I wanted to see the graph for a message thread that was ~29000 messages long

**Comment by dsouzarc** [comment]
This is the first time I heard of this issue (or that it was reported). Were you able to view the graphs of any other conversations?

**Comment by ritvikupadhyaya** [comment]
Yes almost all other convos that I had were fine. However they were significantly smaller in number of messages!

**Comment by dsouzarc** [comment]
What are your laptop specs? This app is very computationally-expensive, especially at a large number of messages, so it might crash on some laptops. 

I only have one conversation with more than 29,000 messages and the initial load time is slow, but my 2015 MB Pro (16GB RAM, 2.8 GHz Intel Core i7) powers through it. A friend with a similar laptop was able to view graphs of a conversation with over 52,000 messages, athough it was also - initially - slow.

Can you run the app side-by-side with Activity Monitor and let me know how the RAM/CPU changes?

**Comment by ritvikupadhyaya** [comment]
I mean its almost the same. I have the 13" with 8 gigs of memory. Which I still feel is a lot. I ll try to see what the problem is.

**Comment by dsouzarc** [comment]
Yeah, clone the master repo on GitHub, open it in Xcode, run it, and let me know what the error message is - I'm curious as well

**Comment by rlarson7** [comment]
I'm crashing as well trying to load. Even when opening through xcode.
![screen shot 2016-09-10 at 1 18 43 pm](https://cloud.githubusercontent.com/assets/11442236/18412638/39fe5b54-7759-11e6-8f2a-2b479ef49a81.png)

**Comment by dsouzarc** [comment]
@rlarson7 @ritvikupadhyaya Try the latest version - I believe I fixed the bug

[Link to .app](https://www.dropbox.com/sh/804msuitbz47gjm/AAAaR5QTdVv8pIRsO9NHZtI7a?dl=0)

**Comment by jxmorris12** [comment]
The app just worked for me with a conversation with 250,000 messages (and 500,000 total)

**Comment by rlarson7** [comment]
Is there a way to export all messages as a text file?

**Comment by dsouzarc** [comment]
@rlarson7 I can look into implementing that. What format are you thinking of for a text file? 

`date phoneNumber messageText`

or 

`phoneNumber date messageText`

or 

`personName date messageText`

**Comment by ritvikupadhyaya** [comment]
@dsouzarc if you have not started, I would go with the 2nd option, `phoneNumber date messageText` just because that is how Apple does it in their imessage clipboard implementation. If it is a contact then maybe replace the number with the contact details (full name etc)

**Comment by rlarson7** [comment]
Yea id agree with that...

Reid

**Comment by ritvikupadhyaya** [comment]
> Yea id agree with that...
> 
> Reid

**Comment by dsouzarc** [comment]
Sorry for my delayed response @ritvikupadhyaya and @rlarson7 
Try out this version on Dropbox [https://www.dropbox.com/s/ytzdwrwzqzmz11s/iMessage%20Analyzer%20-%20Export.zip?dl=0](https://www.dropbox.com/s/ytzdwrwzqzmz11s/iMessage%20Analyzer%20-%20Export.zip?dl=0)

When you run the app, look at the menu bar at the top. There should be a menu item called "Export", which will allow you to export it asa txt file and CSV

**Comment by ritvikupadhyaya** [comment]
Worked for me! Also I dont know if its an apple thing but the newest messages are not being loaded into the app. But the export was fine!

**Comment by dsouzarc** [comment]
Yeah, it's another issue that I have to fix. I'll close this issue in the mean time because that message issue is already listed

**Comment by dsouzarc** [comment]
Out of curiosity, when is the last message that is being loaded? I'm running into a bug when analyzing my Mac Messages where sometimes my last message is from Dec 27th, 2016, and other times is from Jan 8th, 2017 (the actual/correct value)
