### ISSUE TITLE
App is launched but window does not pop up

### ISSUE THREAD

**Issue by meronxo** [dsouzarc/iMessageAnalyzer#3]
I have attempted to open the analyzer multiple times.  The top right hand corner shows that the app is opened on my mac, but no window pops up.  What could be the problem?

**Comment by dsouzarc** [comment]
I think the window is opening somewhere off-screen - that issue sometimes occurs on older laptops with lower screen resolutions. 
I just re-downloaded the latest version of the .app and the window opened up perfectly for me, so it's not an issue of a missing window.  

Try pressing the "F3" button or selecting "Window" from the tool bar on top and then clicking on "iMessageAnalyzer". Let me know if the problem persists.
